# AMAZON NON-SUSTAINABLE PRODUCT SALES VS AMAZON 'SUSTAINABLE' PRODUCTS

In [67]:
#Includes packages and imports that maybe used throughout this notebook
import pandas as pd
import numpy as np
import warnings
from sklearn.model_selection import train_test_split

# Ignore warning messages.
warnings.filterwarnings("ignore")

Data set link reference of Dummy Data https://www.kaggle.com/datasets/suddharshan/retail-price-optimization

Methods used to simulate dummy data of sales from Amazon

In [68]:
# Create a new DataFrame
df = pd.DataFrame()

# Creating dummy data in reference to the 'RetailPrice' data set
# Calculated the variance and standard deviation to generate a number within the range
dummy_data = []
dummy_data2 = []
total_dataset = 1000
directory_path = "../Project3/Datasets/DummyData.csv"
directory_path2 = "../Project3/Datasets/DummyData2.csv"

def get_non_negative_normal(loc, scale):
    while True:
        value = np.random.normal(loc=loc, scale=scale)
        if value >= 0:
            return value

def generateRandomData():
    # All the values are genereated from the mean and variance of a referenced dataframe    
    for i in range(total_dataset):
        qty = get_non_negative_normal(loc =  14.495562, scale = np.sqrt(2.384992e+02))
        total_price = get_non_negative_normal(loc =  1422.708728, scale = np.sqrt(2.890419e+06))
        freight_price  = get_non_negative_normal(loc = 20.682270, scale = np.sqrt(1.016430e+02))
        unit_price = get_non_negative_normal(loc = 106.496800, scale = np.sqrt(5.803845e+03))
        product_name_lengh = get_non_negative_normal(loc = 48.720414, scale = np.sqrt(8.874986e+01))
        product_description_lengh = get_non_negative_normal(loc = 767.399408, scale = np.sqrt(4.292936e+05))
        product_photos_qty = get_non_negative_normal(loc = 1.994083, scale = np.sqrt(2.017743e+00))
        product_weight_g = get_non_negative_normal(loc = 1847.498521, scale = np.sqrt(5.174754e+06))
        product_score = get_non_negative_normal(loc = 4.085503, scale = np.sqrt(5.383397e-02))
        customers = get_non_negative_normal(loc = 81.028107, scale = np.sqrt(3.850893e+03))
        weekday = get_non_negative_normal(loc = 21.773669, scale = np.sqrt(9.724019e-01))
        weekend  = get_non_negative_normal(loc = 8.658284, scale = np.sqrt(4.978720e-01))
        holiday = get_non_negative_normal(loc = 1.494083, scale = np.sqrt(8.844094e-01))
        month = get_non_negative_normal(loc = 6.192308, scale = np.sqrt(1.052000e+01))
        year = get_non_negative_normal(loc = 2017.525148, scale = np.sqrt(2.497370e-01))
        s = get_non_negative_normal(loc = 14.644970, scale = np.sqrt(1.423315e+02))
        volume  = get_non_negative_normal(loc = 10664.627219, scale = np.sqrt(8.414029e+07))
        comp_1 = get_non_negative_normal(loc = 79.452054, scale = np.sqrt(2.297607e+03))
        ps1 = get_non_negative_normal(loc = 4.159467, scale = np.sqrt(1.479912e-02))
        fp1 = get_non_negative_normal(loc = 18.597610, scale = np.sqrt(8.848294e+01))
        comp_2 = get_non_negative_normal(loc = 92.930079, scale = np.sqrt(2.448396e+03))
        ps2 = get_non_negative_normal(loc = 4.123521, scale = np.sqrt(4.292744e-02))
        fp2 = get_non_negative_normal(loc = 18.620644, scale = np.sqrt(4.127001e+01))
        comp_3 = get_non_negative_normal(loc = 84.182642, scale = np.sqrt(2.279660e+03))
        ps3 = get_non_negative_normal(loc = 4.002071, scale = np.sqrt(5.442533e-02))
        fp3 = get_non_negative_normal(loc = 17.965007, scale = np.sqrt(3.061692e+01))
        lag_price = get_non_negative_normal(loc = 107.399684, scale = np.sqrt(5.925098e+03))

        # Append all the values into the dummy_data array
        dummy_data.append([qty,
                           total_price,
                           freight_price,
                           unit_price,
                           product_name_lengh,
                           product_description_lengh,
                           product_photos_qty,
                           product_weight_g,
                           product_score,
                           customers,
                           weekday,
                           weekend,
                           holiday,
                           month,
                           year,
                           s,
                           volume,
                           comp_1,
                           ps1,
                           fp1,
                           comp_2,
                           ps2,
                           fp2,
                           comp_3,
                           ps3,
                           fp3,
                           lag_price])

def generateRandomDataSustainable():
    # All the values are genereated from the mean and variance of a referenced dataframe

    # Considering the 'Sustainable' products are 75% - 85% more espensive
    increase_unit_rate = np.random.uniform(0.75, 0.85)
    mean_unit_price = 106.496800
    new_mean_unit_price = mean_unit_price + (mean_unit_price * increase_unit_rate)

    # 'Sustainable' products take ~17% of the total market
    mean_qty = 14.495562
    new_mean_qty = mean_qty * 0.17

    for i in range(total_dataset):
        qty = get_non_negative_normal(loc =  new_mean_qty, scale = np.sqrt(2.384992e+02))
        total_price = get_non_negative_normal(loc =  1422.708728, scale = np.sqrt(2.890419e+06))
        freight_price  = get_non_negative_normal(loc = 20.682270, scale = np.sqrt(1.016430e+02))
        unit_price = get_non_negative_normal(loc = new_mean_unit_price, scale = np.sqrt(5.803845e+03))
        product_name_lengh = get_non_negative_normal(loc = 48.720414, scale = np.sqrt(8.874986e+01))
        product_description_lengh = get_non_negative_normal(loc = 767.399408, scale = np.sqrt(4.292936e+05))
        product_photos_qty = get_non_negative_normal(loc = 1.994083, scale = np.sqrt(2.017743e+00))
        product_weight_g = get_non_negative_normal(loc = 1847.498521, scale = np.sqrt(5.174754e+06))
        product_score = get_non_negative_normal(loc = 4.085503, scale = np.sqrt(5.383397e-02))
        customers = get_non_negative_normal(loc = 81.028107, scale = np.sqrt(3.850893e+03))
        weekday = get_non_negative_normal(loc = 21.773669, scale = np.sqrt(9.724019e-01))
        weekend  = get_non_negative_normal(loc = 8.658284, scale = np.sqrt(4.978720e-01))
        holiday = get_non_negative_normal(loc = 1.494083, scale = np.sqrt(8.844094e-01))
        month = get_non_negative_normal(loc = 6.192308, scale = np.sqrt(1.052000e+01))
        year = get_non_negative_normal(loc = 2017.525148, scale = np.sqrt(2.497370e-01))
        s = get_non_negative_normal(loc = 14.644970, scale = np.sqrt(1.423315e+02))
        volume  = get_non_negative_normal(loc = 10664.627219, scale = np.sqrt(8.414029e+07))
        comp_1 = get_non_negative_normal(loc = 79.452054, scale = np.sqrt(2.297607e+03))
        ps1 = get_non_negative_normal(loc = 4.159467, scale = np.sqrt(1.479912e-02))
        fp1 = get_non_negative_normal(loc = 18.597610, scale = np.sqrt(8.848294e+01))
        comp_2 = get_non_negative_normal(loc = 92.930079, scale = np.sqrt(2.448396e+03))
        ps2 = get_non_negative_normal(loc = 4.123521, scale = np.sqrt(4.292744e-02))
        fp2 = get_non_negative_normal(loc = 18.620644, scale = np.sqrt(4.127001e+01))
        comp_3 = get_non_negative_normal(loc = 84.182642, scale = np.sqrt(2.279660e+03))
        ps3 = get_non_negative_normal(loc = 4.002071, scale = np.sqrt(5.442533e-02))
        fp3 = get_non_negative_normal(loc = 17.965007, scale = np.sqrt(3.061692e+01))
        lag_price = get_non_negative_normal(loc = 107.399684, scale = np.sqrt(5.925098e+03))

        # Append all the values into the dummy_data array
        dummy_data2.append([qty,
                           total_price,
                           freight_price,
                           unit_price,
                           product_name_lengh,
                           product_description_lengh,
                           product_photos_qty,
                           product_weight_g,
                           product_score,
                           customers,
                           weekday,
                           weekend,
                           holiday,
                           month,
                           year,
                           s,
                           volume,
                           comp_1,
                           ps1,
                           fp1,
                           comp_2,
                           ps2,
                           fp2,
                           comp_3,
                           ps3,
                           fp3,
                           lag_price])

# Input the randomly generated data into a csv file with headers
def convertToCSV():
    # Create a DataFrame from input_data and output_data
    df = pd.DataFrame(dummy_data, columns=['qty',
                                           'total_price',
                                           'freight_price',
                                           'unit_price',
                                           'product_name_lengh',
                                           'product_description_lengh',
                                           'product_photos_qty',
                                           'product_weight_g',
                                           'product_score',
                                           'customers',
                                           'weekday',
                                           'weekend',
                                           'holiday',
                                           'month',
                                           'year',
                                           's',
                                           'volume',
                                           'comp_1',
                                           'ps1',
                                           'fp1',
                                           'comp_2',
                                           'ps2',
                                           'fp2',
                                           'comp_3',
                                           'ps3',
                                           'fp3',
                                           'lag_price'])

    # Write the DataFrame to the CSV file
    df.to_csv(directory_path, index=False)

# Input the randomly generated data into a csv file with headers
def convertToCSV2():
    # Create a DataFrame from input_data and output_data
    df = pd.DataFrame(dummy_data2, columns=['qty',
                                           'total_price',
                                           'freight_price',
                                           'unit_price',
                                           'product_name_lengh',
                                           'product_description_lengh',
                                           'product_photos_qty',
                                           'product_weight_g',
                                           'product_score',
                                           'customers',
                                           'weekday',
                                           'weekend',
                                           'holiday',
                                           'month',
                                           'year',
                                           's',
                                           'volume',
                                           'comp_1',
                                           'ps1',
                                           'fp1',
                                           'comp_2',
                                           'ps2',
                                           'fp2',
                                           'comp_3',
                                           'ps3',
                                           'fp3',
                                           'lag_price'])

    # Write the DataFrame to the CSV file
    df.to_csv(directory_path2, index=False)

Generating the dummy data

In [69]:
# Generate the first Data set
generateRandomData()
convertToCSV()

# Generate the second Data set for 'sustainable' prodcuts
generateRandomDataSustainable()
convertToCSV2()

#Use pandas to read the csv file
#df = pd.read_csv(directory_path)
df = pd.read_csv(directory_path)
df2 = pd.read_csv(directory_path2)

# Dataframe 1 - Normal Products #

Let us take a look at the data frame to get an idea of what it contains

In [70]:
# Taking a glance at the data set to see what we are working with
df.head().T

,0,1,2,3,4
qty,7.392354,30.666218,17.544505,32.052859,21.249415
total_price,2005.034894,3413.794968,463.877309,1389.980514,1815.436627
freight_price,13.165116,17.157909,22.671937,48.470213,27.913412
unit_price,53.543542,101.495582,141.550878,239.063257,117.919109
product_name_lengh,42.074831,45.552652,51.251566,50.154142,38.916511
product_description_lengh,1077.743209,1338.444563,810.319720,687.568755,1088.116829
product_photos_qty,4.547902,2.808329,1.071751,1.384974,0.837003
product_weight_g,1602.633732,2318.142230,3827.701815,2312.170969,2737.391384
product_score,3.708491,4.522832,4.202191,4.004531,3.725239
customers,51.681667,163.811182,202.763142,104.066516,73.543338
weekday,21.680058,22.236996,21.286806,21.440184,22.453955
weekend,8.506376,7.526641,9.047111,8.841819,8.571305
holiday,0.889332,2.087110,2.764794,1.605667,1.993335
month,8.212345,9.779934,4.497598,9.502939,9.104768
year,2018.567872,2017.701403,2017.854618,2018.394964,2017.617549
s,16.170238,36.814658,33.326353,25.519811,2.742973
volume,23190.659972,17089.818584,20503.838254,19598.465278,9048.488700
comp_1,74.788133,112.978619,76.920367,72.872765,220.167590
ps1,4.222847,4.396287,4.063947,4.205836,4.145033
fp1,27.409483,11.468807,28.429275,20.954905,2.222205
comp_2,134.684199,189.280485,163.667187,110.739805,124.577262
ps2,4.093014,4.220480,4.045911,3.954231,4.211148
fp2,19.322416,15.470040,18.180557,29.353520,8.842630
comp_3,154.317583,73.397451,16.831923,160.915243,122.442225
ps3,3.837762,4.019289,4.267995,3.929482,4.245470
fp3,15.224564,16.057460,20.135006,13.778238,24.995374
lag_price,95.005252,140.877873,235.759987,43.819423,147.151960

In [71]:
# Looking at the information of the data set
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   qty                        1000 non-null   float64
 1   total_price                1000 non-null   float64
 2   freight_price              1000 non-null   float64
 3   unit_price                 1000 non-null   float64
 4   product_name_lengh         1000 non-null   float64
 5   product_description_lengh  1000 non-null   float64
 6   product_photos_qty         1000 non-null   float64
 7   product_weight_g           1000 non-null   float64
 8   product_score              1000 non-null   float64
 9   customers                  1000 non-null   float64
 10  weekday                    1000 non-null   float64
 11  weekend                    1000 non-null   float64
 12  holiday                    1000 non-null   float64
 13  month                      1000 non-null   float64
 14  year                       1000 non-null   float64
 15  s                          1000 non-null   float64
 16  volume                     1000 non-null   float64
 17  comp_1                     1000 non-null   float64
 18  ps1                        1000 non-null   float64
 19  fp1                        1000 non-null   float64
 20  comp_2                     1000 non-null   float64
 21  ps2                        1000 non-null   float64
 22  fp2                        1000 non-null   float64
 23  comp_3                     1000 non-null   float64
 24  ps3                        1000 non-null   float64
 25  fp3                        1000 non-null   float64
 26  lag_price                  1000 non-null   float64
dtypes: float64(27)
memory usage: 211.1 KB

Checking the shape of the dataset

In [72]:
print(f"Columns: {df.shape[1]}\nSamples: {df.shape[0]}")

Columns: 27
Samples: 1000

Checking for NAN values

In [73]:
any(df.isna().sum() > 0)

False

Show general analysis of the data frame

In [74]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
qty,1000.0,19.631493,12.460218,0.034966,9.550183,18.375373,27.611519,65.175441
total_price,1000.0,1986.839360,1274.154484,1.219996,1031.146549,1786.058399,2746.387782,7251.530153
freight_price,1000.0,21.154648,9.579323,0.404416,14.349308,20.925603,27.610072,52.284494
unit_price,1000.0,119.066365,63.594322,0.667186,71.221516,114.400284,159.253324,330.441664
product_name_lengh,1000.0,49.028753,9.450253,18.260884,42.699471,49.101803,55.014565,77.948499
product_description_lengh,1000.0,914.283065,550.727615,6.038401,481.265662,853.921016,1275.417051,2807.247561
product_photos_qty,1000.0,2.281387,1.235147,0.015891,1.330294,2.252972,3.107647,6.808455
product_weight_g,1000.0,2784.028690,1778.848544,16.271348,1377.888920,2584.766024,3941.610585,8805.083387
product_score,1000.0,4.081403,0.234492,3.363430,3.925878,4.080833,4.235983,4.809381
customers,1000.0,93.622287,51.449838,0.334564,55.158980,90.253681,125.559347,273.479050
weekday,1000.0,21.778023,1.006816,17.891429,21.109971,21.738746,22.485142,24.999508
weekend,1000.0,8.680400,0.706430,6.091059,8.210392,8.699719,9.151083,10.837178
holiday,1000.0,1.565587,0.827438,0.004258,0.920280,1.546505,2.131629,4.739532
month,1000.0,6.461038,3.016193,0.064048,4.272235,6.347913,8.465986,17.281835
year,1000.0,2017.510462,0.505568,2015.871161,2017.170104,2017.510460,2017.847420,2019.044284
s,1000.0,16.983999,9.666170,0.071627,9.428848,16.176644,23.672112,52.832794
volume,1000.0,12351.308488,7484.987252,0.149065,6565.165497,11424.197071,17050.680679,43210.056988
comp_1,1000.0,83.532407,42.753065,0.588000,52.526068,80.606252,112.941002,247.999071
ps1,1000.0,4.162444,0.119667,3.789041,4.082508,4.159695,4.244079,4.557577
fp1,1000.0,19.335741,8.888083,0.244443,12.993183,19.058094,25.396481,49.062333
comp_2,1000.0,96.884342,45.644571,0.265019,63.085645,95.796093,127.532082,231.732551
ps2,1000.0,4.124158,0.211426,3.332010,3.969668,4.121455,4.260071,4.896449
fp2,1000.0,18.994205,6.298724,0.907056,14.859905,19.044205,23.328221,38.127060
comp_3,1000.0,89.636669,44.310223,0.067231,57.213307,88.047823,120.240874,237.700398
ps3,1000.0,4.002460,0.242665,3.171433,3.847342,4.008805,4.169979,4.713570
fp3,1000.0,17.951916,5.466400,1.748606,14.139700,18.000880,21.606929,34.752901
lag_price,1000.0,120.733596,66.803472,0.267823,71.728077,116.474853,162.279100,385.365446

### Dataframe preparation

We need to remove any parameter that has no relevance in solving the problem. When analyzing a dataframe, all parameters have an inpact on each other. Therefore we do not want a paramter that is irrelevant to impact our main result

In [76]:
# Create a list of parameters that we do not believe contributes to the target
columns_to_drop = ['product_name_lengh',
                   'product_description_lengh',
                   'product_photos_qty',
                   'product_weight_g',
                   's',
                   'weekday',
                   'weekend',
                   'holiday',
                   'month',
                   'year',
                   'comp_1',
                   'ps1',
                   'fp1',
                   'comp_2',
                   'ps2',
                   'fp2',
                   'comp_3',
                   'ps3',
                   'fp3',
                   'lag_price']

df = df.drop(columns = columns_to_drop)

Calculate the revenue and profit while adding them to the dataframe

In [77]:
# Create a revenue column in the data frame
# Revenue = total_quantity * total_price
df["revenue"] = df['qty'] * df['total_price']
total_revenue = df['revenue'].sum()

# Create a profit column in the data frame
# profit = revenue - freight_price
df["profit"] = df["revenue"] - df["freight_price"]
total_profit = df['profit'].sum()

print("The total revenue of items in the data frame:", total_revenue, 
      "\nThe total profit of all the items:", total_profit)

The total revenue of items in the data frame: 40134032.12834768
The total profit of all the items: 40112877.47989054

Looking at the dataframe after the cacluations

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   qty            1000 non-null   float64
 1   total_price    1000 non-null   float64
 2   freight_price  1000 non-null   float64
 3   unit_price     1000 non-null   float64
 4   product_score  1000 non-null   float64
 5   customers      1000 non-null   float64
 6   volume         1000 non-null   float64
 7   revenue        1000 non-null   float64
 8   profit         1000 non-null   float64
dtypes: float64(9)
memory usage: 70.4 KB

The dataframe has values with varying ranges for each column, we will standardize the values to be more consistent

In [80]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = MinMaxScaler()

# Fit and transform the DataFrame
scaled_data = scaler.fit_transform(df)

# Create a new DataFrame with scaled values
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)
# scaled_df.to_excel('scaledOutput.xlsx', index = False)

Create a new Dataframe with parameters that most consumers look at when comparing a 'normal' product vs a 'sustainable' product

In [81]:
new_df = df[['profit', 'qty', 'total_price', 'product_score', 'customers'  ]].copy()

Apply a train-test split to determine train and test the accuracy of the models

In [82]:
#Splitting into train and test sets
X = new_df.loc[:,new_df.columns != 'profit']     
y = new_df['profit']  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state = 42)

Apply different machine learning algorithms

In [83]:
from sklearn.model_selection import KFold, ShuffleSplit, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn import svm

cv = ShuffleSplit(n_splits = 10, test_size = 0.2)

#Linear Regression
model1 = LinearRegression()
model1.fit(X_train, y_train)
cross_val_scores1 = cross_val_score(model1, X_train, y_train, cv = cv)
train_accuracy1 = model1.score(X_train, y_train)
test_accuracy1 = model1.score(X_test, y_test)

#Random Forest
model2 = RandomForestRegressor(random_state = True, warm_start = True, criterion = 'absolute_error', max_depth = 100)
model2.fit(X_train, y_train)
cross_val_scores2 = cross_val_score(model2, X_train, y_train, cv = cv)
train_accuracy2 = model2.score(X_train, y_train)
test_accuracy2 = model2.score(X_test, y_test)

#KNN
model3 =KNeighborsRegressor()
model3.fit(X_train, y_train)
cross_val_scores3 = cross_val_score(model3, X_train, y_train, cv = cv)
train_accuracy3 = model3.score(X_train, y_train)
test_accuracy3 = model3.score(X_test, y_test)

#Decision Tree
model4 = DecisionTreeRegressor()
model4.fit(X_train, y_train)
cross_val_scores4 = cross_val_score(model4, X_train, y_train, cv = cv)
train_accuracy4 = model4.score(X_train, y_train)
test_accuracy4 = model4.score(X_test, y_test)

#SVR
model5 = svm.SVR()
model5.fit(X_train, y_train)
cross_val_scores5 = cross_val_score(model5, X_train, y_train, cv = cv)
train_accuracy5 = model5.score(X_train, y_train)
test_accuracy5 = model5.score(X_test, y_test)

#Printing Results
print(f'Linear Regression\nTraining set:{100 * train_accuracy1:.2f}%\nTest set:{100 * test_accuracy1:.2f}%\nMean Cross-Validation Score:{cross_val_scores1.mean():.2f}')
print('----------------------------------------')
print(f'Random Forest Regressor\nTraining set:{100 * train_accuracy2:.2f}%\nTest set:{100 * test_accuracy2:.2f}\nMean Cross-Validation Score:{cross_val_scores2.mean():.2f}')
print('----------------------------------------')
print(f'K-Nearest Neighbor\nTraining set:{100 * train_accuracy3:.2f}%\nTest set:{100 * test_accuracy3:.2f}\nMean Cross-Validation Score:{cross_val_scores3.mean():.2f}')
print('----------------------------------------')
print(f'Decision Tree Regressor\nTraining set:{100 * train_accuracy4:.2f}%\nTest set:{100 * test_accuracy4:.2f}\nMean Cross-Validation Score:{cross_val_scores4.mean():.2f}')
print('----------------------------------------')
print(f'Support Vector Regression\nTraining set:{100 * train_accuracy5:.2f}%\nTest set:{100 * test_accuracy5:.2f}\nMean Cross-Validation Score:{cross_val_scores5.mean():.2f}')

Linear Regression
Training set:85.98%
Test set:82.30%
Mean Cross-Validation Score:0.84
----------------------------------------
Random Forest Regressor
Training set:99.61%
Test set:98.55
Mean Cross-Validation Score:0.99
----------------------------------------
K-Nearest Neighbor
Training set:69.35%
Test set:47.83
Mean Cross-Validation Score:0.55
----------------------------------------
Decision Tree Regressor
Training set:100.00%
Test set:93.94
Mean Cross-Validation Score:0.92
----------------------------------------
Support Vector Regression
Training set:-8.85%
Test set:-6.42
Mean Cross-Validation Score:-0.11

# Dataframe 2 - Sustainable Products

Check the shape of the dataset

In [85]:
# Taking a glance at the data set to see what we are working with
df2.head().T

,0,1,2,3,4
qty,9.241083,31.363743,8.086574,8.594257,6.579795
total_price,664.034879,789.593962,2855.586583,429.529284,3518.433106
freight_price,19.376190,15.595333,24.329801,26.836032,19.646039
unit_price,125.380034,188.022329,286.037469,203.402667,205.635909
product_name_lengh,56.346480,50.521137,48.781770,29.640468,51.216004
product_description_lengh,735.521941,1543.867331,1073.305387,847.316035,1213.333172
product_photos_qty,4.365917,3.106763,2.130809,1.906657,5.129398
product_weight_g,1323.806279,3831.871944,2933.875521,1530.497383,4649.131321
product_score,3.959905,3.951403,4.032429,4.159625,4.023320
customers,124.136966,64.558567,101.386783,201.947490,58.146820
weekday,22.895178,21.172206,21.645379,22.340486,21.630337
weekend,10.034367,10.161846,7.782097,9.905351,9.425380
holiday,0.435586,2.291111,1.869824,2.287990,1.385724
month,4.044796,4.862450,7.650852,7.064541,9.182719
year,2017.272563,2017.484088,2017.310643,2017.532430,2016.986796
s,4.905646,5.227658,5.875930,0.400915,4.342179
volume,7248.669618,10842.622963,6840.294009,6574.817590,6714.770978
comp_1,97.075802,84.261580,57.288927,88.684863,98.917712
ps1,4.085170,4.065074,4.044130,4.116927,4.165925
fp1,18.259442,3.445685,24.760309,11.392951,16.419135
comp_2,10.858172,112.413356,80.887606,144.767340,56.918703
ps2,3.912748,4.257441,3.980549,4.556162,4.028518
fp2,18.500506,13.958997,18.132440,19.460886,18.669219
comp_3,27.102146,39.016529,49.124107,103.191968,112.957063
ps3,4.210664,3.788802,4.077346,3.941730,4.496465
fp3,20.542146,18.847950,12.974354,17.539444,14.836710
lag_price,116.481615,18.906621,152.393712,119.551578,150.822519

In [86]:
# Looking at the information of the data set
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   qty                        1000 non-null   float64
 1   total_price                1000 non-null   float64
 2   freight_price              1000 non-null   float64
 3   unit_price                 1000 non-null   float64
 4   product_name_lengh         1000 non-null   float64
 5   product_description_lengh  1000 non-null   float64
 6   product_photos_qty         1000 non-null   float64
 7   product_weight_g           1000 non-null   float64
 8   product_score              1000 non-null   float64
 9   customers                  1000 non-null   float64
 10  weekday                    1000 non-null   float64
 11  weekend                    1000 non-null   float64
 12  holiday                    1000 non-null   float64
 13  month                      1000 non-null   float64
 14  year                       1000 non-null   float64
 15  s                          1000 non-null   float64
 16  volume                     1000 non-null   float64
 17  comp_1                     1000 non-null   float64
 18  ps1                        1000 non-null   float64
 19  fp1                        1000 non-null   float64
 20  comp_2                     1000 non-null   float64
 21  ps2                        1000 non-null   float64
 22  fp2                        1000 non-null   float64
 23  comp_3                     1000 non-null   float64
 24  ps3                        1000 non-null   float64
 25  fp3                        1000 non-null   float64
 26  lag_price                  1000 non-null   float64
dtypes: float64(27)
memory usage: 211.1 KB

In [87]:
print(f"Columns: {df2.shape[1]}\nSamples: {df2.shape[0]}")

Columns: 27
Samples: 1000

Checking for NAN values

In [88]:
any(df2.isna().sum() > 0)

False

Show general analysis of the data frame

In [89]:
df2.describe().T

,count,mean,std,min,25%,50%,75%,max
qty,1000.0,13.169797,10.128638,0.062487,5.351575,10.626297,18.491151,54.512985
total_price,1000.0,2060.377401,1269.901545,4.906793,1095.390642,1883.270544,2850.938492,6413.367817
freight_price,1000.0,21.341677,9.432496,0.029492,14.833324,20.856095,27.920939,50.125660
unit_price,1000.0,192.251561,75.708065,2.441332,141.878832,193.061873,244.403161,410.786639
product_name_lengh,1000.0,49.070174,9.561261,12.192632,42.316231,49.158638,55.664603,75.626079
product_description_lengh,1000.0,908.090372,523.918316,3.219224,510.558404,853.926792,1265.164916,2675.825620
product_photos_qty,1000.0,2.220919,1.209761,0.000378,1.354858,2.123387,3.057924,7.076016
product_weight_g,1000.0,2568.356236,1654.379903,1.809560,1189.071415,2351.932313,3661.703215,8667.309726
product_score,1000.0,4.086503,0.225983,3.351968,3.932166,4.084109,4.240165,4.836869
customers,1000.0,93.252635,52.588491,0.298149,51.894346,89.859850,129.527724,274.411407
weekday,1000.0,21.743062,0.990542,18.264257,21.091185,21.767032,22.341780,25.203361
weekend,1000.0,8.631248,0.708356,5.888771,8.162198,8.613380,9.139329,10.536190
holiday,1000.0,1.613658,0.826651,0.001236,1.037863,1.576418,2.156955,4.269689
month,1000.0,6.235833,2.997230,0.001464,4.066386,6.052776,8.315914,16.550265
year,1000.0,2017.508199,0.509153,2015.838185,2017.171472,2017.525029,2017.860465,2018.939566
s,1000.0,16.626361,10.128514,0.056337,8.950006,15.543942,23.494394,53.242821
volume,1000.0,12861.553292,7586.261745,3.266064,6718.710976,12345.893620,18029.224385,39523.091651
comp_1,1000.0,84.303120,43.871282,0.948233,50.452929,82.383282,113.380397,253.269799
ps1,1000.0,4.153609,0.124103,3.741896,4.075840,4.149294,4.237127,4.517624
fp1,1000.0,19.281827,8.731059,0.005904,12.845002,18.945188,25.112536,48.893011
comp_2,1000.0,96.031531,45.431865,1.514806,61.836553,94.969172,126.418606,228.315279
ps2,1000.0,4.127147,0.205759,3.424290,3.989079,4.127395,4.266206,4.861813
fp2,1000.0,19.060206,6.531321,1.645390,14.446617,19.090434,23.243766,41.374368
comp_3,1000.0,88.425254,43.259255,0.391441,57.814096,86.294755,118.138822,222.838463
ps3,1000.0,4.009033,0.232580,3.305514,3.851921,4.015315,4.171357,4.723169
fp3,1000.0,17.941416,5.368795,0.690936,14.348879,18.039973,21.475153,34.327532
lag_price,1000.0,116.537706,65.413945,0.139419,63.817960,110.869053,158.661063,356.173203

### Dataframe preparation

In [91]:
# There are some parameters in the dataframe that we do not need to help solve our problem
columns_to_drop = ['product_name_lengh',
                   'product_description_lengh',
                   'product_photos_qty',
                   'product_weight_g',
                   's',
                   'weekday',
                   'weekend',
                   'holiday',
                   'month',
                   'year',
                   'comp_1',
                   'ps1',
                   'fp1',
                   'comp_2',
                   'ps2',
                   'fp2',
                   'comp_3',
                   'ps3',
                   'fp3',
                   'lag_price']

df2 = df2.drop(columns = columns_to_drop)

Calculate the total amount of items and the total price

In [92]:
# The number of total items in the data set
total_items = df2['qty'].sum()

# The total amount for every item in 'qty'
total_price = df2['total_price'].sum()

print("The total amount of items in the data frame:", total_items, 
      "\nThe total price of all the items:", total_price)

The total amount of items in the data frame: 13169.79719989464
The total price of all the items: 2060377.4010045424

Calculate the revenue and the profit

In [93]:
# Create a revenue column in the data frame
# Revenue = total_quantity * total_price
df2["revenue"] = df2['qty'] * df2['total_price']
total_revenue = df2['revenue'].sum()

# Create a profit column in the data frame
# profit = revenue - freight_price
df2["profit"] = df2["revenue"] - df2["freight_price"]
total_profit = df2['profit'].sum()

print("The total revenue of items in the data frame:", total_revenue, 
      "\nThe total profit of all the items:", total_profit)

The total revenue of items in the data frame: 27367827.715640966
The total profit of all the items: 27346486.03831213

The values of the dataframe contains various ranges for each column, we will scale them to be more consistent

In [99]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = MinMaxScaler()

# Fit and transform the DataFrame
scaled_data = scaler.fit_transform(df2)

# Create a new DataFrame with scaled values
scaled_df = pd.DataFrame(scaled_data, columns=df2.columns)
# scaled_df.to_excel('scaledOutput2.xlsx', index = False)

Creating a new dataframe with the parameters considered when comparing 'normal' vs 'sustainable' products

In [94]:
new_df2 = df2[['profit', 'qty', 'total_price', 'product_score', 'customers'  ]].copy()

Train-test split

In [95]:
#Splitting into train and test sets
X = new_df2.loc[:,new_df2.columns != 'profit']     
y = new_df2['profit']  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state = 42)

Applying different machine learning algorithms

In [96]:
from sklearn.model_selection import KFold, ShuffleSplit, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn import svm

cv = ShuffleSplit(n_splits = 10, test_size = 0.2)

#Linear Regression
model11 = LinearRegression()
model11.fit(X_train, y_train)
cross_val_scores1 = cross_val_score(model11, X_train, y_train, cv = cv)
train_accuracy1 = model11.score(X_train, y_train)
test_accuracy1 = model11.score(X_test, y_test)

#Random Forest
model22 = RandomForestRegressor(random_state = True, warm_start = True, criterion = 'absolute_error', max_depth = 100)
model22.fit(X_train, y_train)
cross_val_scores2 = cross_val_score(model22, X_train, y_train, cv = cv)
train_accuracy2 = model22.score(X_train, y_train)
test_accuracy2 = model22.score(X_test, y_test)

#KNN
model33 =KNeighborsRegressor()
model33.fit(X_train, y_train)
cross_val_scores3 = cross_val_score(model33, X_train, y_train, cv = cv)
train_accuracy3 = model33.score(X_train, y_train)
test_accuracy3 = model33.score(X_test, y_test)

#Decision Tree
model44 = DecisionTreeRegressor()
model44.fit(X_train, y_train)
cross_val_scores4 = cross_val_score(model44, X_train, y_train, cv = cv)
train_accuracy4 = model44.score(X_train, y_train)
test_accuracy4 = model44.score(X_test, y_test)

#SVR
model55 = svm.SVR()
model55.fit(X_train, y_train)
cross_val_scores5 = cross_val_score(model55, X_train, y_train, cv = cv)
train_accuracy5 = model55.score(X_train, y_train)
test_accuracy5 = model55.score(X_test, y_test)

#Printing Results
print(f'Linear Regression\nTraining set:{100 * train_accuracy1:.2f}%\nTest set:{100 * test_accuracy1:.2f}%\nMean Cross-Validation Score:{cross_val_scores1.mean():.2f}')
print('----------------------------------------')
print(f'Random Forest Regressor\nTraining set:{100 * train_accuracy2:.2f}%\nTest set:{100 * test_accuracy2:.2f}\nMean Cross-Validation Score:{cross_val_scores2.mean():.2f}')
print('----------------------------------------')
print(f'K-Nearest Neighbor\nTraining set:{100 * train_accuracy3:.2f}%\nTest set:{100 * test_accuracy3:.2f}\nMean Cross-Validation Score:{cross_val_scores3.mean():.2f}')
print('----------------------------------------')
print(f'Decision Tree Regressor\nTraining set:{100 * train_accuracy4:.2f}%\nTest set:{100 * test_accuracy4:.2f}\nMean Cross-Validation Score:{cross_val_scores4.mean():.2f}')
print('----------------------------------------')
print(f'Support Vector Regression\nTraining set:{100 * train_accuracy5:.2f}%\nTest set:{100 * test_accuracy5:.2f}\nMean Cross-Validation Score:{cross_val_scores5.mean():.2f}')

Linear Regression
Training set:83.10%
Test set:83.83%
Mean Cross-Validation Score:0.84
----------------------------------------
Random Forest Regressor
Training set:99.81%
Test set:98.17
Mean Cross-Validation Score:0.98
----------------------------------------
K-Nearest Neighbor
Training set:56.06%
Test set:24.69
Mean Cross-Validation Score:0.26
----------------------------------------
Decision Tree Regressor
Training set:100.00%
Test set:94.44
Mean Cross-Validation Score:0.95
----------------------------------------
Support Vector Regression
Training set:-11.25%
Test set:-10.13
Mean Cross-Validation Score:-0.12

Analysis

When we applied the different machine learning models to the dataframe, we learned that the Linear Regression Model and the Random Forest Regressor model performed the best for both the dataframe with Normal Products and the dataframe with Sustainable products. When given the same parameters and when give the same model, we can predict the profit that will be gained of a normal product vs a sustainable one

Using Linear Regression Model to predicts which one will earn a greater profit when given the same parameters

In [98]:
# Parameters for the inputs of the predict method = 'qty', 'total_price', 'product_score', 'customers'

print('Linear Regression')
print('The predicted profit for a normal product is', model1.predict([[100, 5000, 5, 100]]))
print('The predicted profit for a sustainable product is', model11.predict([[100, 5000, 5, 100]]))
print('-------------------------------------------------------------------------------------------')
print('Random Forest Regressor')
print('The predicted profit for a normal product is', model2.predict([[100, 5000, 5, 100]]))
print('The predicted profit for a sustainable product is', model22.predict([[100, 5000, 5, 100]]))
print('-------------------------------------------------------------------------------------------')
print('KNN')
print('The predicted profit for a normal product is', model3.predict([[100, 5000, 5, 100]]))
print('The predicted profit for a sustainable product is', model33.predict([[100, 5000, 5, 100]]))
print('-------------------------------------------------------------------------------------------')
print('Ddecision Tree Regressor')
print('The predicted profit for a normal product is', model4.predict([[100, 5000, 5, 100]]))
print('The predicted profit for a sustainable product is', model44.predict([[100, 5000, 5, 100]]))
print('-------------------------------------------------------------------------------------------')
print('Support Vector Regression')
print('The predicted profit for a normal product is', model5.predict([[100, 5000, 5, 100]]))
print('The predicted profit for a sustainable product is', model55.predict([[100, 5000, 5, 100]]))

Linear Regression
The predicted profit for a normal product is [259574.63027524]
The predicted profit for a sustainable product is [259063.55279341]
-------------------------------------------------------------------------------------------
Random Forest Regressor
The predicted profit for a normal product is [216708.182901]
The predicted profit for a sustainable product is [181075.98804845]
-------------------------------------------------------------------------------------------
KNN
The predicted profit for a normal product is [135851.79780031]
The predicted profit for a sustainable product is [128638.00645636]
-------------------------------------------------------------------------------------------
Ddecision Tree Regressor
The predicted profit for a normal product is [301510.6506641]
The predicted profit for a sustainable product is [181494.01737962]
-------------------------------------------------------------------------------------------
Support Vector Regression
The predicted profit for a normal product is [28626.30456229]
The predicted profit for a sustainable product is [17348.26458711]